# Capstone - Berlin Venues consolidated

## Introduction
In the last years, Berlin has become more interesting for tech start-ups investors [1]. To satisfy the demand for an increasing number of young people, the capital of Germany has attracted many other diverse businesses. The idea of this research is to cluster venues in Berlin to make recommendations to investors interested to start a new business in Berlin. This project is based on the capsote Toronto project with the addition of two more data sources, namely the Berlins crimes in 2019 and the Berlin population density by the same year. The data is described below.

Observations: this essay may be strongly affected after the corona lockdown at the finish of 2020.

## Audience
This project may be interest to:
1.  Small entrepreneurs of any kind who are interested in settled done in Berlin.
2.  Financiers, aiming to invest in the City.
3.  Governmental entities willing to facilitate the funding of many from private investors
4.  General public looking for radicate in Berlin and wants to know more where to live.

## Data

This research will use three source of data:

* Population: Berlin's neighborhood with the corresponding zip codes and population density are can be found in wikipeda [2] 
* Crimes: Classification of crimes in Berlin, sorted by Neighborhood, can be found in a csv on Klage [3].
* Venues: it will be used Foursquare.

The expected table looks like:

| zip code   |   population/km2   |  Robery...Burglary | Restaurant...Fitness Studio |
|----------  |   :-------------:  |  ------:   |  -----:       |
| 101        | 9576.000           |    43..5      |   1..0           |
| 102        | 10.427             |    12..3      |   0..1           |
| 103        | 11.181             |    1..5       |   0..1           |

### Population Table

In [18]:
import pandas as pd
url = r'https://de.wikipedia.org/wiki/Verwaltungsgliederung_Berlins'
tables = pd.read_html(url) # Returns list of all tables on page
population = tables[1] # Select table of interest
population.head()

,Nr.,Ortsteil,Bezirk,Fläche(km²),Einwohner[2](31. Dezember 2019),Einwohnerpro km²
0,101,Mitte,Mitte,1070,102.465,9576.000
1,102,Moabit,Mitte,772,80.495,10.427
2,103,Hansaviertel,Mitte,53,5.926,11.181
3,104,Tiergarten,Mitte,517,14.881,2878.000
4,105,Wedding,Mitte,923,86.806,9405.000

### Crimes

In [19]:
import pandas as pd
crimes = pd.read_csv("Berlin_crimes.csv")
crimes.head()

,Year,District,Code,Location,Robbery,Street_robbery,Injury,Agg_assault,Threat,Theft,Car,From_car,Bike,Burglary,Fire,Arson,Damage,Graffiti,Drugs,Local
0,2012,Mitte,10111,Tiergarten Süd,70,46,586,194,118,2263,18,328,120,68,16,4,273,26,171,1032
1,2012,Mitte,10112,Regierungsviertel,65,29,474,123,142,3203,10,307,170,37,10,4,380,124,98,870
2,2012,Mitte,10113,Alexanderplatz,242,136,1541,454,304,8988,81,792,822,275,49,27,1538,522,435,3108
3,2012,Mitte,10114,Brunnenstraße Süd,52,25,254,60,66,1916,86,192,396,131,14,5,428,122,213,752
4,2012,Mitte,10221,Moabit West,130,51,629,185,199,2470,94,410,325,161,42,22,516,64,259,1403

# literature
[1] https://www.berlin.de/en/business-and-economy/business-developement/5615902-5886496-for-startups-and-founders.en.html

[2] https://de.wikipedia.org/wiki/Verwaltungsgliederung_Berlins

[3] https://www.kaggle.com/danilzyryanov/crime-in-berlin-2012-2019/version/4